export { default as Navbar } from './Navbar'
export { default as Cryptocurrencies } from './Cryptocurrencies'
export { default as CryptoDetailes } from './CryptoDetails'
export { default as Exchanges } from './Exchanges'
export { default as Homepage } from './Homepage'
export { default as News } from './News'
export { default as Predictions } from './Predictions'
